{{- if and .Values.acmObservability.multiClusterObservability.enabled .Values.acmObservability.multiClusterObservability.metricObjectStorage.externalSecret.enabled }}
{{- $objectStorage := .Values.acmObservability.multiClusterObservability.metricObjectStorage }}
{{- $meta := dict "name" $objectStorage.name "namespace" .Values.acmObservability.namespace "root" $ "component" "thanos-object-storage" "labels" (dict) "annotations" (dict "argocd.argoproj.io/sync-wave" "2") }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
{{ include "openshift-observability.metadata" $meta }}
spec:
  refreshInterval: {{ $objectStorage.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: {{ $objectStorage.name }}
    creationPolicy: Owner
  data:
    - secretKey: {{ $objectStorage.key }}
      remoteRef:
        key: {{ $objectStorage.externalSecret.vaultKey }}
        property: {{ $objectStorage.key }}
{{- end }}
