{{- if include "openshift-observability.clusterConfig.shouldApply" . | trim }}
{{- $name := include "openshift-observability.userWorkload.cronjobName" . }}
{{- $meta := dict "name" $name "namespace" "openshift-monitoring" "root" $ "component" "user-workload-monitoring" "labels" (dict) "annotations" (dict "argocd.argoproj.io/sync-wave" "5") }}
---
apiVersion: batch/v1
kind: CronJob
{{ include "openshift-observability.metadata" $meta }}
spec:
  schedule: {{ .Values.monitoring.userWorkload.schedule | quote }}
  # if previous Job is still running, skip execution of a new Job
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ .Values.monitoring.userWorkload.activeDeadlineSeconds }}
      template:
        {{- include "openshift-observability.userWorkload.podTemplate" . | nindent 8 }}
{{- end }}
